baseURL = 'https://docs.bashfulrobot.com/'
languageCode = 'en-us'
title = 'Bashfulrobot MFG'
theme = 'hugo-geekdoc'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocRepo = 'https://github.com/bashfulrobot/pdocs'
  geekdocEditPage = true
  geekdocSearch = true
  geekdocSearchShowParent = true
  geekdocDarkMode = true
  geekdocDarkModeCode = true
  geekdocDarkModeDim = true
  geekdocAnchor = true
  geekdocAnchorCopy = true
  geekdocCollapseSection = true
  geekdocImageLazyLoading = true
  geekdocToC = 3
  geekdocLogo = '/images/brmfg-logo-circle-200.png'

