baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Documentation'
theme = 'hugo-geekdoc'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocRepo = 'https://github.com/bashfulrobot/pdocs'
  geekdocSearch = true
  geekdocDarkMode = true
